 language: node_js
 node_js:
 - stable
 script:
 - npm run coverage
 branches:
   only:
   - development
notifications:
    email:
      recipients:
        - me@cjosullivan.net     # uae your own
        - cjosullivan@hotmail.co.uk   # uae other (optional)
      on_success: never        # default: change
      on_failure: always       # default: always